### ISSUE TITLE
Python3 not installed - service-runner fails

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#111]
They key point here is that this may well fail for scripted installs.

https://github.com/openenergymonitor/EmonScripts/blob/b1400d10bb8a3ee64ec88fb94e1ff723e1bf38a8/install/main.sh#L64

Only Python not Python3 is installed. Required for service-runner.

Should also be done in the update script.

https://github.com/openenergymonitor/EmonScripts/blob/067386ad29e67d4bc2f148339a91366b8bbc8da4/update/main.sh#L27

Why does this not simply install Python3?

https://github.com/openenergymonitor/EmonScripts/blob/067386ad29e67d4bc2f148339a91366b8bbc8da4/update/main.sh#L36

**Comment by TrystanLea** [comment]
Seems that I missed that line, I wonder fi we change to just:

     sudo apt-get install -y git build-essential gettext 

whether that would work correctly, I imagine it would

**Comment by borpin** [comment]
No because with just a core install, python3 is never installed now for service runner.

Also, for some distributions Python is installed by default (Ubuntu) and not others (Debian). This may be why we have seen inconsistencies in the past.

We should simply try and install all dependencies, those already satisfied will be ignored.

**Comment by TrystanLea** [comment]
I've changed this line now to python3-pip and dev and moved gettext to apache
https://github.com/openenergymonitor/EmonScripts/blob/master/install/main.sh#L64
