### ISSUE TITLE
pip/pip3 should not be run as sudo

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#112]
https://github.com/openenergymonitor/EmonScripts/blob/cff186a832e44d6692dae5b4217c381f42c94ab7/update/emonhub.sh#L37

pip3 should not be run as sudo (plenty of direction on this in the docs).

**Comment by TrystanLea** [comment]
Will that now cause a problem now that we have started with sudo?

**Comment by borpin** [comment]
It shouldn't.... (famous last words).

**Comment by TrystanLea** [comment]
These have been moved to the emonhub repo but are still installed with sudo
https://github.com/openenergymonitor/emonhub/blob/master/install.sh#L22

Redis client is still installed with sudo, not sure if required...
https://github.com/openenergymonitor/EmonScripts/blob/master/install/redis.sh#L20

**Comment by TrystanLea** [comment]
Testing installation on minimalmodbus on a pi yesterday, I noticed that I did need to install with sudo, I think the reason for this is that emonhub is ran under the emonhub username and so cannot access packages installed under pi?

**Comment by borpin** [comment]
New image does not use sudo.
