### ISSUE TITLE
a single makefile to install the **whole** stack

### ISSUE THREAD

**Issue by alexandrecuer** [openenergymonitor/EmonScripts#133]
I would like to introduce a new way to install the stack via a makefile

it's just a proposal to simplify the maintenance because in the scripts, there are really a lot of files to manage and it can become quickly complicated. 

I don't have much experience with this method yet, but I feel like it's pretty robust and portable. The makefile is self-supporting and generates all the necessary files, including service files, conf files for apache...it also reduces a little the usage of sed.

so I wanted to share this with you :

https://github.com/dromotherm/sandbox/blob/master/makefile

to download the script (where you want but `/opt/openenergymonitor/` can be a good location)   : 

```
wget https://raw.githubusercontent.com/dromotherm/sandbox/master/makefile
```
`make help`  will give you the recipes

things are to be launched brick by brick. To update the operating system : 

```
make osupdate
```

To install the dependancies :

```
make apache
make mysql
make php
make redis
make mosquitto
```
To install the core : 
```
make emoncms
make apacheconf
make feedwriter
make service-runner
make emoncms_mqtt
```
To install modules :
```
make module name=graph
make module name=dashboard
```

best

Alex

**Comment by TrystanLea** [comment]
Thankyou for this proposal @alexandrecuer when I get a good opportunity I will take a closer look at this to learn how it works and consider it's adoption.
