### ISSUE TITLE
Sync module not installed correctly

### ISSUE THREAD

**Issue by linuxtim** [openenergymonitor/EmonScripts#141]
The sync module gets installed under /opt/openenergymonitor/Modules/sync/sync-module - in this location, it's not activated (so that the sync icon is not visible in the Setup list etc.).

To activate it, I had to manually:

    mkdir /opt/openenergymonitor/Modules/
    mv /var/www/emoncms/Module/sync /opt/openenergymonitor/Modules/sync
    ln -s /opt/openenergymonitor/Modules/sync/sync-module sync

**Comment by TrystanLea** [comment]
Hello @linuxtim tested this on a couple of builds now and it seems to install in the correct location for me. I will close this issue for now, feel free to reopen if needed
