### ISSUE TITLE
PHP8 & making the emoncms_mqtt service work

### ISSUE THREAD

**Issue by alexandrecuer** [openenergymonitor/EmonScripts#144]
This is not an issue, just a reminder

To have emoncms_mqtt service working with php8 :
```
git clone --branch=php8 https://github.com/nismoryco/Mosquitto-PHP
cd Mosquitto-PHP
phpize && ./configure && make && sudo make install
```
right now this patch is not merged in the php8 branch of the official repo https://github.com/mgdm/Mosquitto-PHP

tested on a RPI3 with ubuntu22 (https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04&architecture=server-arm64+raspi)

**Comment by TrystanLea** [comment]
Thanks @alexandrecuer I've updated the script to use this fork and branch as it is still not merged into the main repository. I've forked a copy of that branch to github.com/openenergymonitor/Mosquitto-PHP so we have a static copy of it there
