### ISSUE TITLE
Update systems with new logrotate schema

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#167]
#163 updates new installs but does not update existing installs.

**Comment by TrystanLea** [comment]
Ok thanks, noted

**Comment by borpin** [comment]
@TrystanLea 

Just did a fresh install with the SD Image, 

Switched all components to `master`.

First I wasn't expecting this to just happen, a popup is needed.
Second, where is the log going?
Third, the logrotate update didn't work correctly

![image](https://user-images.githubusercontent.com/1322749/216785772-47fe2def-fbd6-4f89-bb1f-105abf9c0d0c.png)

I don't know where this is being picked up from

**Comment by borpin** [comment]
#168 should solve at update.

**Comment by TrystanLea** [comment]
Thanks
