### ISSUE TITLE
introduction of a global variable git_repo

### ISSUE THREAD

**Issue by alexandrecuer** [openenergymonitor/EmonScripts#20]
@TrystanLea : Would you be willing to introduce a new variable in config.ini, in order to be able to test forks or branches more easily and also to separate the config from the code, even if I understand that for you https://github.com/emoncms and https://github.com/openenergymonitor are constants
it would be a question of creating a variable named git_repo, which we could define the following way :
```
declare -A git_repo
git_repo[emoncms_core]=https://github.com/emoncms/emoncms.git
git_repo[config]=https://github.com/emoncms/config.git
git_repo[graph]=https://github.com/emoncms/graph.git
git_repo[dashboard]=https://github.com/emoncms/dashboard.git
git_repo[app]=https://github.com/emoncms/app.git
git_repo[wifi]=https://github.com/emoncms/wifi.git
git_repo[device]=https://github.com/emoncms/device.git
git_repo[demandshaper]=https://github.com/emoncms/demandshaper.git
git_repo[sync]=https://github.com/emoncms/sync.git
git_repo[backup]=https://github.com/emoncms/backup.git
git_repo[usefulscripts]=https://github.com/emoncms/usefulscripts.git
git_repo[postprocess]=https://github.com/emoncms/postprocess.git
git_repo[emonhub]=https://github.com/emoncms/emonhub.git
emonhub_branch=master
.....
```

the scripts that would need to be modified would be all the "git clone" scripts (emoncms_core.sh, emoncms_modules.sh, emonhub.sh) maybe we could extend it to emonsd.sh, emonpilcd.sh, firmware.sh, wifiap.sh, just to be clean 

if somebody wants to test its own fork, he just needs to modify config.ini without going in the sh files...

if this seems OK for yu, I can propose a PR...if it is not suitable, no problem

Alex

**Comment by TrystanLea** [comment]
sure Im happy with that! 

Thanks for your help @alexandrecuer
