### ISSUE TITLE
config.ini executeable

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#27]
https://github.com/openenergymonitor/EmonScripts/blob/e22ed870790246c5733817d3cb1b46e5ccd364b5/install/config.ini#L3

I note that there are executable statements in a file with an extension `.ini`.

It seems to me this is a bad idea.

I think the settings (the `ini` part - i.e. the values) are separated from a `config.sh` file to process the config.

this will make modifying the settings easier.

**Comment by TrystanLea** [comment]
I think the following should work, I haven’t tested it during a full install yet
https://github.com/openenergymonitor/EmonScripts/compare/load_config_sh?expand=1

@alexandrecuer any thoughts on this?

**Comment by borpin** [comment]
That looks an interesting approach! Like it.

**Comment by borpin** [comment]
Could the same be done for the `backup.cfg` that is needed by both PHP and shell?

**Comment by TrystanLea** [comment]
I've merged the load_config_sh branch for testing. I will take a look at backup.cfg

**Comment by alexandrecuer** [comment]
@TrystanLea : nice ! It is a better solution than the previous config.ini with an executable part
