### ISSUE TITLE
Update message on checking config.ini

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#28]
@TrystanLea The message on checking the config.ini is fine in that it interrupts the install, but the user will have no idea where the file is nor how to trigger the install to start again.

https://github.com/openenergymonitor/EmonScripts/blob/e22ed870790246c5733817d3cb1b46e5ccd364b5/install/main.sh#L30

I suggest 2 commands one for editing the file and another for running the install are included in the message.

echo "cd $openenergymonitor_dir/EmonScripts/install/"
echo "nano config.ini"
echo "./main.sh"

My bash is not good enough to know if that is right to include a variable 😀.

**Comment by TrystanLea** [comment]
Thanks @borpin added this in:
https://github.com/openenergymonitor/EmonScripts/tree/load_config_sh
