### ISSUE TITLE
Install config module only if emonhub is installed

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#29]
https://github.com/openenergymonitor/EmonScripts/blob/e22ed870790246c5733817d3cb1b46e5ccd364b5/install/emonhub.sh#L5

The installation of the `config` module should be only done if emonhub is installed.

https://github.com/openenergymonitor/EmonScripts/blob/e22ed870790246c5733817d3cb1b46e5ccd364b5/install/config.ini#L63

**Comment by TrystanLea** [comment]
I've added a comment to config.ini to suggest commenting out the config module from the list of modules to install in this case: https://github.com/openenergymonitor/EmonScripts/commit/c2ea0c002d390c970f66ce3d56bbf96e69133c46

The install process for these are separate unfortunately, an automated approach would require specific hardcoded checks.. 

is it worth adding this in?

**Comment by borpin** [comment]
Personally I think so. It is a quick check when the module is about to be installed to check and see if `install_emonhub=true` is true.
