### ISSUE TITLE
Non-Pi Logrotate

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#35]
A marker for this

https://community.openenergymonitor.org/t/emonsd-next-steps-filesystem-logrotate/10693/199

**Comment by TrystanLea** [comment]
Implemented, thanks for the example config, see:

https://github.com/openenergymonitor/EmonScripts/commit/1eafefa4d84deeb90a66335c541da5234174585f

https://github.com/openenergymonitor/EmonScripts/commit/39398d6fb22025ec455c4a2f8bbdbfad3761a03c

**Comment by borpin** [comment]
Is this right?

https://github.com/openenergymonitor/EmonScripts/blob/3349eda148d977651d433f624f3aeb28a293acb0/install/non_emonsd.sh#L2

Looks ideal.

**Comment by TrystanLea** [comment]
Fixed thanks: https://github.com/openenergymonitor/EmonScripts/commit/b804e32b6c644eea42087f623ed0bed4cc922d0c
