### ISSUE TITLE
emoncmsdbupdate needs to be modified to work with new settings object

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#38]
https://github.com/openenergymonitor/EmonScripts/blob/b1beb5d01554732500927f6588276b9569a70522/common/emoncmsdbupdate.php#L11

@TrystanLea This need to be updated to work with new settings object.

**Comment by TrystanLea** [comment]
Thanks @borpin now fixed.

**Comment by borpin** [comment]
@TrystanLea did you fix the UsefulScripts and EmonPi versions as well?

**Comment by TrystanLea** [comment]
Yes I did fix those
