### ISSUE TITLE
Update all modules to 'stable'?

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#40]
https://github.com/openenergymonitor/EmonScripts/blob/3cb8ddcfa3c9e03efe8dc9b4551624134fd40688/install/emonsd.config.ini#L53

Should all repos be 'stable' now?

**Comment by TrystanLea** [comment]
yes! :) done https://github.com/openenergymonitor/EmonScripts/commit/b8522b773fbb4088626c768aee6738fbf54a58da
