### ISSUE TITLE
non pi user no sudo password

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#45]
If a non-pi user (i.e. not Raspbian) they need to be setup not to require a password when using sudo.

https://stackoverflow.com/questions/21659637/how-to-fix-sudo-no-tty-present-and-no-askpass-program-specified-error

Probably best at start of `main.sh`

**Comment by TrystanLea** [comment]
I've added this as a pre-install step here, step 7 https://github.com/openenergymonitor/EmonScripts/issues/44

**Comment by borpin** [comment]
I think it should be part of the 'non-pi' actions - easy enough to script as it is done elsewhere for other things like wifi.

**Comment by borpin** [comment]
Included as part of the documentation.
