### ISSUE TITLE
arm_freq setting never used?

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#60]
https://github.com/openenergymonitor/EmonScripts/blob/79dc389c8427180c5049d247c883d7f5a4ae28cf/install/emonsd.sh#L53-L53

According to the [Raspbian documentation](https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md), no Pi has a default frequency of 800.

I suggest this line is removed from the script.

**Comment by TrystanLea** [comment]
Removed here
https://github.com/openenergymonitor/EmonScripts/commit/984d9c9e04765d808c6d9ea9c594465c130e6c6b
