### ISSUE TITLE
Still mod_rewrite

### ISSUE THREAD

**Issue by cassiel74** [openenergymonitor/EmonScripts#70]
Just followed this guide 
https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md

Got this error while registering user
`404 Not Found: Is modrewrite configured on your system?`

Everything untouched exept for apache2 dir set to /home/www/emoncms

Any hint?

**Comment by borpin** [comment]
Those install guides are depreciated in favour of the scripted install.

Note the message at the top.

**Comment by cassiel74** [comment]
Got it. I finally managed to run install scripts separately.

**Comment by borpin** [comment]
Great, if you are done then could you close the issue please.
