### ISSUE TITLE
the config.ini in update may not reflect the installed locations

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#72]
There are 3 hardcoded paths in the `updae/config.ini` - these may not reflect the choices made during the installation process.

https://github.com/openenergymonitor/EmonScripts/blob/e3fee4d36819f6589f806898509f374f5660cc66/update/config.ini#L5

The `update/config.ini` file should be added to the '.gitignore' and this file generated generated as part of the installation process with the selected paths.

An alternative solution might be to simply copy the install `config.ini` to the update folder.

There is a similar issue with the backup script IIRC.

**Comment by TrystanLea** [comment]
I've now fully removed the use of update/config.ini and am now using install/load_config.sh instead:
https://github.com/openenergymonitor/EmonScripts/commit/063a755c6f7193a6a43433b5561f1d08566c6f88
