### ISSUE TITLE
Modify LCD service install & update scripts

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonScripts#93]
https://github.com/openenergymonitor/EmonScripts/blob/ac100a39845cbb4b790afb0c37103c20c8b6683a/install/emonpilcd.sh#L4-L4

Move the install file to the `emonpi/lcd` folder.

Ref https://github.com/openenergymonitor/emonpi/pull/120

**Comment by borpin** [comment]
Added update to the issue as that will need to be done as well especially in the move to Python3.

**Comment by alexandrecuer** [comment]
See
https://github.com/openenergymonitor/emonpi/pull/121
and
https://github.com/openenergymonitor/EmonScripts/pull/97
